networks:
  iots-bridge:
    name: iots_bridge

secrets:
  influx-token:
    file: ./secrets/influx_token

services:
  iots-influxdb:
    image: influxdb:2
    container_name: iots-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ${INFLUX_ROOT}/influxdb2-data:/var/lib/influxdb2
      - ${INFLUX_ROOT}/influxdb2-config:/etc/influxdb2
      - ${INFLUX_ROOT}/environmental_sensor_telemetry_data.csv:/environmental_sensor_telemetry_data.csv
      - ${INFLUX_ROOT}/scripts:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influx-token
    networks:
      - iots-bridge
    secrets:
      - influx-token

  data-provider:
    build:
      context: ./EnvironmentalSensorTelemetry
      dockerfile: Dockerfile
      no_cache: true
    container_name: data-provider
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_TOKEN_FILE=${INFLUXDB_TOKEN_FILE}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - iots-bridge
    secrets:
      - influx-token

  grpcui:
    image: wongnai/grpcui
    container_name: grpcui
    environment:
      GRPCUI_SERVER: ${DATA_PROVIDER_SERVER}
    depends_on:
      - data-provider
    ports:
      - "8081:8080"
    networks:
      - iots-bridge
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5